<?php

/*
 * *** DO NOT EDIT THIS FILE!!! ***
 * Any changes made in this file will be lost on future upgrades.  Any of these
 * values which are specified in the configure.php.local file will override
 * those contained in this file.
 */
$applicationName = "Backup Media Management";
$applicationInstance = "Development";

// REMOVE THE FOLLOWING LINES FROM THE configure.php.local file:
include 'configure.php.local';
?>
